#! /bin/sh

topic="${2:-HEAD}"
base="${1:-master}"

fork_rev ()
{
	git rev-list    \
		--date-order \
		--reverse    \
		--boundary   \
	${topic}...${base} |\
	\
	grep '^-' |\
	cut -c2-  |\
	head -1
}

fork=$(fork_rev)

if [ -z "${fork}" ]; then
	fork="${base}"
fi

echo "${fork}".."${topic}"

# fork=$(git rev-list --first-parent "^${topic}" "${base}" |\
# tail -1)
