#! /usr/bin/env node

require('console-ultimate/global').replace()

var minimist = require('minimist')


var commands =
{
	t: require('./lib/t')
}


var cmd  = process.argv[2]
var argv = process.argv.slice(3)
var args = minimist(argv)

;(commands[cmd] || notFound)(args, cmd, argv)


function notFound (_, cmd)
{
	console.error('command `%s` not found', cmd)
	process.exit(-1)
}
