#! /bin/sh

space=' '
bold='\033[1m'
reset='\033[22m'

PROMPT=$(echo -en "${bold}↳${reset}${space}")
PS2=$(echo -en "${bold}…${reset}${space}")

cd $(dirname ${0})
run=$(pwd)

precmd ()
{
	"${run}/git-headup"
}
