#! /bin/sh

space=' '
bold='\033[1m'
reset='\033[22m'

PROMPT=$(echo -en "${bold}↳${reset}${space}")
PS2=$(echo -en "${bold}…${reset}${space}")

precmd ()
{
	echo "${bold}| ${USER}:${HOST}${reset}"
}
